name: Java CI/CD

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 22
        uses: actions/setup-java@v3
        with:
          java-version: '22'
          distribution: 'temurin'
      - run: mvn clean package
      - name: Run tests
        run: mvn test
    
      - name: Verify Swagger Docs
        run: |
          echo "Checking OpenAPI spec generation"
          test -f target/classes/META-INF/openapi.json || exit 1
        
      - name: Upload Artifacts
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: application-jar
          path: target/*.jar